version: '3.8'

services:
  postgres:
    build:
      context: ./   
      dockerfile: Dockerfile  
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345 
    ports:
      - "5432:5432" 
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
